### ISSUE TITLE
Nuki Opener does not work from HomeAssistant but from NukiApp it works

### ISSUE THREAD

**Issue by stefancvetkovic** [kvj/hass_nuki_ng#115]
Hello,
I have a strange behavior in my home.
Im using Nuki Lock and Nuki opener.
Nuki Lock works 100% from Ha, and form Nuki App
But Nuki opener, does not work from HA, only from Nuki App
Also I can see that mine `binary_sensor.bottom_door_opener_ring_action` gets the state changes (when I ring on my intercome in front of enter the building, I set automatic open the door)

This is mine lovelace setup:
```
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    entity: lock.nuki_front_door_lock
    show_state: true
    name: Front Door Lock
#ock.nuki_front_door_lock works
  - type: button
    entity: lock.bottom_door_opener_lock
    name: Bottom Door Lock
    show_state: true
#lock.bottom_door_opener_lock does not work
```

Any hints? Why mine nuki opener lock does not locks/unlocks from HA?
