### ISSUE TITLE
SERVICE LOCK_N_GO?

### ISSUE THREAD

**Issue by andybali** [kvj/hass_nuki_ng#30]
The Service LOCK_N_GO isn´t implemented?
Nuki 3.0 without Bridge

**Comment by kvj** [comment]
not yet, but good idea to have it

**Comment by faxmaster** [comment]
Hi! First thanks for the great work, your integration is already vastly superior to the official one! The only reason I didn't delete the other one yet is the missing Lock'N'Go service. So +1 for that feature

**Comment by KitHubek** [comment]
I wait for this too

**Comment by agarbato** [comment]
This could be nice but It's something you can do with an automation.

I've a scene where I set to ON an input boolean (I call it 'leaving')
With google home I trigger the scene with voice command "I'm leaving"

After that I've the following automation that unlock and then lock the door after 40secs so I have time to go out :-)
You can also arm an alarm system if you have one.

```
alias: LeavingOpenThenLock
description: ''
trigger:
  - platform: state
    entity_id: input_boolean.leaving
    from: 'off'
    to: 'on'
condition: []
action:
  - service: lock.unlock
    data: {}
    target:
      device_id: mylockid
  - delay:
      hours: 0
      minutes: 0
      seconds: 40
      milliseconds: 0
  - service: lock.lock
    data: {}
    target:
      device_id: mylockid
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.leaving
mode: single
```

**Comment by Larx** [comment]
I would like to have this implemented, too. IMHO it's better to use a ready-made and builtin function, if available, than to rely on additional HA automations. Is this still on the todo-list?

**Comment by kvj** [comment]
There's an API for that:
```yaml
service: nuki_ng.execute_action
data:
  action: lock_n_go
target:
  device_id: 83f592f5c6d885fe4698618afb5cb129
```

![Screenshot from 2022-09-02 06-15-23](https://user-images.githubusercontent.com/159124/188057819-0f7abc53-5b68-4326-929c-afaacb149fb7.png)
