### ISSUE TITLE
Ring as trigger possible?

### ISSUE THREAD

**Issue by Friedi1970** [kvj/hass_nuki_ng#38]
I’d say it is not really an issue but I wonder whether it might be possible to fetch the ringing of the door bell with the opener and use it as a trigger?

**Comment by ZzetT** [comment]
I think that's possible:

```
alias: Notification if bell rings
trigger:
  - platform: state
    entity_id: binary_sensor.nuki_opener_ring_action
    from: 'off'
    to: 'on'
condition: []
action:
  - device_id: A3F
    domain: mobile_app
    type: notify
    message: Doorbell rang
    title: Doorbell
mode: single
```
