### ISSUE TITLE
Example in the Readme doesn't unlatch Nuki Lock

### ISSUE THREAD

**Issue by hnykda** [kvj/hass_nuki_ng#43]
Hi,

when I try the example from the Readme:

```
type: button
entity: lock.nuki_front_door_lock
tap_action:
  action: call-service
  service: lock.open
  service_data: {}
  target:
    entity_id: lock.nuki_front_door_lock
name: Nuki
```
(with my entity_id of the lock of course), it doesn't unlatch - it only "opens" (the lock shows white LED - so it gets the signal, but doesn't unlatch) on "Unlock" action (long press on the button in Lovelace UI and clicking "unlock"). I can't make it unlatch actually.
